apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-tracker-uploads
  namespace: project-tracker
  labels:
    app.kubernetes.io/name: project-tracker
    app.kubernetes.io/component: api-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
